#!/usr/bin/env bash
#
# VPS Setup - Configuration Generator (non-interactive)
# Usage: ./generate_config.sh [--docker] [--php] [--caddy] [--nodejs] [--nvm] [--bun] [--security]
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONFIG_FILE="$PROJECT_ROOT/provision_config.yml"

# Defaults
DOCKER=false
PHP_FPM=false
CADDY=false
NODEJS=false
NVM=false
BUN=false
SECURITY=false
RUNTIME_USER="${USER:-root}"

usage() {
    echo "Usage: $0 [options]"
    echo ""
    echo "Options:"
    echo "  --docker      Enable Docker + Docker Compose"
    echo "  --php         Enable PHP-FPM"
    echo "  --caddy       Enable Caddy reverse proxy"
    echo "  --nodejs      Enable Node.js (system-wide)"
    echo "  --nvm         Enable NVM (Node version manager)"
    echo "  --bun         Enable Bun runtime"
    echo "  --security    Enable security hardening"
    echo "  --all         Enable all components"
    echo "  --user USER   Set runtime user for NVM/Bun"
    echo "  --help        Show this help"
    echo ""
    echo "Example:"
    echo "  $0 --docker --nodejs --bun --security"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --docker)
            DOCKER=true
            shift
            ;;
        --php)
            PHP_FPM=true
            shift
            ;;
        --caddy)
            CADDY=true
            shift
            ;;
        --nodejs)
            NODEJS=true
            shift
            ;;
        --nvm)
            NVM=true
            shift
            ;;
        --bun)
            BUN=true
            shift
            ;;
        --security)
            SECURITY=true
            shift
            ;;
        --all)
            DOCKER=true
            PHP_FPM=true
            CADDY=true
            NODEJS=true
            NVM=true
            BUN=true
            SECURITY=true
            shift
            ;;
        --user)
            RUNTIME_USER="$2"
            shift 2
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

# Generate config
timestamp=$(date '+%Y-%m-%d %H:%M:%S')

cat > "$CONFIG_FILE" << EOF
---
# VPS Provisioning Configuration
# Generated by generate_config.sh on ${timestamp}

vps_components:
  docker: ${DOCKER}
  php_fpm: ${PHP_FPM}
  caddy: ${CADDY}
  nodejs: ${NODEJS}
  nvm: ${NVM}
  bun: ${BUN}
  security: ${SECURITY}

runtime_user: "${RUNTIME_USER}"
EOF

echo "Configuration generated: $CONFIG_FILE"
echo ""
cat "$CONFIG_FILE"
