#!/usr/bin/env bash
#
# VPS Setup - Interactive Component Selection Menu
# Usage: ./menu.sh [--run]
#
# Options:
#   --run    Execute ansible-playbook after generating config
#

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONFIG_FILE="$PROJECT_ROOT/provision_config.yml"

# Components definition
declare -A COMPONENTS=(
    ["docker"]="Docker + Docker Compose|Container runtime with compose support"
    ["php_fpm"]="PHP-FPM|PHP FastCGI Process Manager (no Apache/Nginx)"
    ["caddy"]="Caddy|Reverse proxy with automatic HTTPS"
    ["nodejs"]="Node.js (system-wide)|JavaScript runtime via NodeSource"
    ["nvm"]="NVM|Node Version Manager (per-user)"
    ["bun"]="Bun|Fast JavaScript/TypeScript runtime"
    ["security"]="Security Hardening|UFW firewall, fail2ban, SSH hardening"
)

# Default selection (1 = selected, 0 = not selected)
declare -A SELECTED=(
    ["docker"]=1
    ["php_fpm"]=0
    ["caddy"]=0
    ["nodejs"]=1
    ["nvm"]=0
    ["bun"]=1
    ["security"]=1
)

# Component order for display
COMPONENT_ORDER=("docker" "php_fpm" "caddy" "nodejs" "nvm" "bun" "security")

# Additional config
RUNTIME_USER="${USER:-root}"
ANSIBLE_USER=""
SSH_HOST=""

# Clear screen and show header
show_header() {
    clear
    echo -e "${CYAN}${BOLD}"
    echo "╔═══════════════════════════════════════════════════════════════╗"
    echo "║              VPS Setup - Component Selection                  ║"
    echo "╚═══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    echo ""
}

# Show menu options
show_menu() {
    show_header

    echo -e "${BOLD}Select components to install:${NC}"
    echo -e "${YELLOW}(Press number to toggle, 'd' to confirm, 'q' to quit)${NC}"
    echo ""

    local i=1
    for comp in "${COMPONENT_ORDER[@]}"; do
        local name desc
        IFS='|' read -r name desc <<< "${COMPONENTS[$comp]}"
        local status="○"
        local color="${RED}"

        if [[ ${SELECTED[$comp]} -eq 1 ]]; then
            status="●"
            color="${GREEN}"
        fi

        echo -e "  ${BOLD}$i${NC}. [${color}${status}${NC}] ${BOLD}${name}${NC}"
        echo -e "      ${BLUE}${desc}${NC}"
        echo ""
        ((i++))
    done

    echo -e "${YELLOW}────────────────────────────────────────────────────────────────${NC}"
    echo ""
    echo -e "  ${BOLD}r${NC}. Configure runtime user: ${CYAN}${RUNTIME_USER}${NC}"
    echo -e "  ${BOLD}h${NC}. Configure target host: ${CYAN}${SSH_HOST:-not set}${NC}"
    echo -e "  ${BOLD}u${NC}. Configure ansible user: ${CYAN}${ANSIBLE_USER:-not set}${NC}"
    echo ""
    echo -e "${YELLOW}────────────────────────────────────────────────────────────────${NC}"
    echo -e "  ${BOLD}d${NC}. ${GREEN}Done - Generate config and exit${NC}"
    echo -e "  ${BOLD}q${NC}. ${RED}Quit without saving${NC}"
    echo ""
}

# Toggle component selection
toggle_component() {
    local index=$1
    local comp="${COMPONENT_ORDER[$((index-1))]}"

    if [[ ${SELECTED[$comp]} -eq 1 ]]; then
        SELECTED[$comp]=0
    else
        SELECTED[$comp]=1
    fi
}

# Generate provision_config.yml
generate_config() {
    local timestamp
    timestamp=$(date '+%Y-%m-%d %H:%M:%S')

    echo -e "${CYAN}Generating configuration...${NC}"

    cat > "$CONFIG_FILE" << EOF
---
# VPS Provisioning Configuration
# Generated by menu.sh on ${timestamp}

# Component selection
vps_components:
EOF

    for comp in "${COMPONENT_ORDER[@]}"; do
        local value="false"
        if [[ ${SELECTED[$comp]} -eq 1 ]]; then
            value="true"
        fi
        echo "  ${comp}: ${value}" >> "$CONFIG_FILE"
    done

    cat >> "$CONFIG_FILE" << EOF

# Runtime user for NVM/Bun
runtime_user: "${RUNTIME_USER}"

# Target configuration
EOF

    if [[ -n "$ANSIBLE_USER" ]]; then
        echo "ansible_user: \"${ANSIBLE_USER}\"" >> "$CONFIG_FILE"
    fi

    echo "" >> "$CONFIG_FILE"

    echo -e "${GREEN}✓ Configuration saved to: ${CONFIG_FILE}${NC}"
    echo ""
    cat "$CONFIG_FILE"
    echo ""
}

# Run ansible-playbook
run_ansible() {
    cd "$PROJECT_ROOT"

    if [[ ! -f "$CONFIG_FILE" ]]; then
        echo -e "${RED}Error: No configuration file found. Run menu first.${NC}"
        exit 1
    fi

    local ansible_opts=()
    ansible_opts+=("-i" "inventory/hosts.yml")
    ansible_opts+=("-e" "@${CONFIG_FILE}")

    if [[ -n "$SSH_HOST" ]]; then
        # Add temporary host to inventory
        ansible_opts+=("-e" "ansible_host=${SSH_HOST}")
    fi

    echo -e "${CYAN}Running ansible-playbook...${NC}"
    echo -e "${YELLOW}Command: ansible-playbook playbooks/site.yml ${ansible_opts[*]}${NC}"
    echo ""

    ansible-playbook playbooks/site.yml "${ansible_opts[@]}"
}

# Main menu loop
main() {
    local auto_run=false

    if [[ "${1:-}" == "--run" ]]; then
        auto_run=true
    fi

    while true; do
        show_menu

        read -r -n 1 -s choice
        echo ""

        case "$choice" in
            [1-7])
                toggle_component "$choice"
                ;;
            r|R)
                echo -n "Enter runtime user [${RUNTIME_USER}]: "
                read -r input
                RUNTIME_USER="${input:-$RUNTIME_USER}"
                ;;
            h|H)
                echo -n "Enter target host (IP or hostname): "
                read -r SSH_HOST
                ;;
            u|U)
                echo -n "Enter ansible user: "
                read -r ANSIBLE_USER
                ;;
            d|D)
                generate_config

                if $auto_run; then
                    echo ""
                    echo -n "Run ansible-playbook now? [Y/n]: "
                    read -r confirm
                    if [[ "${confirm:-y}" =~ ^[Yy]?$ ]]; then
                        run_ansible
                    fi
                fi
                exit 0
                ;;
            q|Q)
                echo -e "${YELLOW}Exiting without saving.${NC}"
                exit 0
                ;;
            *)
                ;;
        esac
    done
}

# Run main
main "$@"
